### ISSUE TITLE
Support for public forks of libraries

### ISSUE THREAD

**Issue by suspiciousRaccoon** [stvnksslr/uv-migrator#70]
hi! /ᐠ. ̫ .ᐟ\ฅ

I tried to migrate a poetry project that uses some public forks instead of the original dependencies but they didn't seem to migrate over.

Something like this:
```toml
[tool.poetry.dependencies]
dependency = { git= "https://github.com/user/library.git", branch="my-branch" }

```
Migrated into:
```toml
[project]
dependencies = [
    "dependency>=1.0"
]
```

When it should have been:
```toml
[project]
dependencies = [
    "dependency>=1.0"
]
[tool.uv.sources]
dependency = { git = "https://github.com/user/library.git", branch="my-branch" }

```

After `uv-migrator`  runs, running:
```bash
uv add git+https://github.com/user/library.git --branch my-branch
```
Adds the the fork correctly, but it would be nice if `uv-migrator` did all the work.

I tried this with uv-migrator 2025.7.0 and uv 0.5.26.

That aside, thanks for making this tool (づ๑•ᴗ•๑)づ♡
